# Put configuration options here
CONFIG_ZMK_RGB_UNDERGLOW_ON_START=n
CONFIG_ZMK_BACKLIGHT_ON_START=n
CONFIG_ZMK_PM_SOFT_OFF=n
CONFIG_ZMK_KEYBOARD_NAME="Oreo"
CONFIG_ZMK_SLEEP=y # Enable deep sleep support
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=900000 # Milliseconds of inactivity before entering deep sleep
